### ISSUE TITLE
Changes in ssf.conf to generate other certificates

### ISSUE THREAD

**Issue by davidmathew** [AndreasHeine/SecurePythonOpcUaServer#1]
Hi @AndreasHeine,

I believe the ssf.conf figure is valid only for generating certificate that work with Basic256Sha256_SignAndEncrypt. What about other policies? What changes do we have to make in ssl.conf to generate certificate and private key for policies such as  Basic256Sha256_Sign, Aes256Sha256RsaPss, Aes128Sha256RsaOaep for both sign and sign&Encrypt?

**Comment by AndreasHeine** [comment]
for that i have to refer to openssl documentation -> https://www.openssl.org/docs/
currently i am using None or Basic256Sha256_SignAndEncrypt
