### ISSUE TITLE
what exactly is the pupose of the certificate?

### ISSUE THREAD

**Issue by Padu98** [AndreasHeine/SecurePythonOpcUaServer#2]
Hi, 
I recently started setting up an OPCUA Server with python. The configuration worked just fine for me but when it comes to the security aspect I get a little bit confused. In the OPCUA docs i red that I server can have a trusted list which specifies who (which clients) have access to the server.  For that purpose the Server should know the public keys of the clients, so that they can authenticate themself (If I got this correct). 
But what exactly is the purpose of the key pair in your project? Are those just to secure the Connection itself so that nobody can read what is transferred between server and client? Or is there also a usecase in terms of limiting the access to specified clients?
And if there is no usecase in limitation is there even a way to limit the access despite using a password?

I am new to this topic I also do not have great experience with using security in general.  Thank in advance,

**Comment by AndreasHeine** [comment]
In this Server!

### Message Security:
```python
    server.load_certificate("certificate.pem")
    server.load_private_key("key.pem")
    server.set_security_policy([
                                    # ua.SecurityPolicyType.NoSecurity,
                                    # ua.SecurityPolicyType.Basic128Rsa15_Sign,
                                    # ua.SecurityPolicyType.Basic128Rsa15_SignAndEncrypt,
                                    # ua.SecurityPolicyType.Basic256Sha256_Sign,
                                    ua.SecurityPolicyType.Basic256Sha256_SignAndEncrypt
                                ])
```
Communication between Client and Server is Signed and Encrypted (Basic256Sha256_SignAndEncrypt)
The server Uses the Certificate and the Key to achieve that.

### Authorisation:
```python
    policyIDs = ["Username"]
    server.set_security_IDs(policyIDs)
    server.user_manager.set_user_manager(user_manager)
```
This Server uses a simple Username/Pw Authorizer


Note "python-opcua" is depricated (not maintained anymore) you should consider using asyncua (opcua-asyncio)! But in both librarys there are no deeper cert checks included, so each with a valid cert will be accepted in terms of message security.
In OPC UA it is also possible to athorize with a cert but this only replaces Username/Pw.
